### ISSUE TITLE
Can you add logout to the backend?

### ISSUE THREAD

**Issue by rjayako** [TaylorRayHoward/ExampleJWT#1]
Loved your tutorial but can you please complete the backend? How do we handle log out with the approach you took? Thanks.

**Comment by coyote963** [comment]
I think logout is handled client side. just set the localstorage jwt to empty

**Comment by rjayako** [comment]
what about the valid tokens from the DB side?

**Comment by coyote963** [comment]
there is not a way to invalidate a jwt token, so I believe no action can be taken on DB side

**Comment by TaylorRayHoward** [comment]
@rjayako There's no such thing as a logout for the backend.  Logging out means removing the token from localStorage client side.  One of the big pluses for JWTs is that you don't need to store any of this data in the database to facilitate a login.  I'll be making a video soon on some strategies to blacklist JWTs.
